### ISSUE TITLE
New volunteer screening

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#1]
Just went into screening for a new volunteer and it seems that when I chose "shift volunteer/weekend manager" as the screening type and hit "submit", the checkmarks for the shifts she's available disappeared. I got a pop-up that indicated I needed to choose availability for shifts, but I know she had marked several.

**Comment by megandalster** [comment]
This one is fixed -- a few additional issues were also fixed so that screenings should now work okay.  Wasn't able to put the fancy date picker onto the steps of the screening -- you'll just have to enter "mm-dd-yy".  Hope that's okay for now.
