### ISSUE TITLE
Vacancy report

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#2]
I tried pulling up a report on the number of vacancies during a two week period in September, and got numerous warnings:
Warning: substr_count() expects parameter 1 to be string, array given in /home/content/00/4393300/html/rmhc-homebase/database/dbShifts.php on line 451

Could be user error!

**Comment by megandalster** [comment]
This one is fixed, along with some addtional issues with reports.  The row headers are now more general, to accommodate the differences between weekdays and weekend days.  Does that look okay, Gretchen?

**Comment by gnoonan** [comment]
Boy, I'm a little late to this game.  Didn't realize until just now that I should reply!  Yes, looks wonderful.  Sorry if I left you hanging.
