### ISSUE TITLE
Log-In Issues

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#4]
I am able to log in with no problem and have full functionality, but others seem unable to view the calendar (the volunteer log-in and Karla's log-in both give a "you don't have permission to access this calendar" message).  A volunteer reported being unable to log-in from home.

**Comment by gnoonan** [comment]
I figured it out!!  I added new weeks but never published them!  So, we're now all set.  Sorry about that!

**Comment by megandalster** [comment]
Okay, thanks!  Allen

On Sep 28, 2015, at 1:51 PM, gnoonan <notifications@github.com<mailto:notifications@github.com>> wrote:

I figured it out!! I added new weeks but never published them! So, we're now all set. Sorry about that!
