### ISSUE TITLE
Odd/Even calendar weeks at the end of the year

### ISSUE THREAD

**Issue by megandalster** [megandalster/rmhc-homebase#7]
Hi Gretchen,

I've found a new issue with the calendar -- that is, at the end of the year persons scheduled for every other week will get scheduled for 2 weeks in a row, which is not good.  

I've fixed the issue and will send Dave the fix in a separate email, with instructions to you for checking it out at your convenience.

Allne

**Comment by gnoonan** [comment]
Thank you Allen!  Glad you caught it now.  I would ask how, but I’m sure I wouldn’t follow . . .
Hope you’re well!
-Gretchen

**Comment by megandalster** [comment]
Hi Gretchen,

I have fixed this issue by making the first week of every year either 0 or 1 depending on whether the last week of the previous year was 53 or 52.  This effectively creates a 2-year cycle, and it guarantees that people on an every-other-week cycle will not be jolted at the end of this year by getting assigned 2 weeks in a row.

Dave, please replace the attached 4 scripts at the root level in the Homebase code base on the rmhcrmaine.orghttp://rmhcrmaine.org server.  Please also let us all know when that is done.  Thanks!

Gretchen, after Dave installs the fix, you should see a slightly different header on the calendar page, looking like this:

**Comment by megandalster** [comment]
I’ve uploaded the new files.

**Comment by megandalster** [comment]
Thanks, Dave.  We have dodged a bullet at the end of 2015!  Allen

On Oct 15, 2015, at 6:21 PM, David Tripp <dave@artopa.com<mailto:dave@artopa.com>> wrote:

I’ve uploaded the new files.

On Oct 15, 2015, at 5:33 PM, Allen Tucker <allen@bowdoin.edu<mailto:allen@bowdoin.edu>> wrote:

Hi Gretchen,

I have fixed this issue by making the first week of every year either 0 or 1 depending on whether the last week of the previous year was 53 or 52.  This effectively creates a 2-year cycle, and it guarantees that people on an every-other-week cycle will not be jolted at the end of this year by getting assigned 2 weeks in a row.

Dave, please replace the attached 4 scripts at the root level in the Homebase code base on the rmhcrmaine.orghttp://rmhcrmaine.org/ server.  Please also let us all know when that is done.  Thanks!

Gretchen, after Dave installs the fix, you should see a slightly different header on the calendar page, looking like this:

<Screen Shot 2015-10-15 at 5.19.49 PM.png>

The header now shows the week number and whether or not it is even or odd at the right.  Moving forward with the “Next Week” tab, notice that even and odd alternate correctly at the end of this year and the beginning of 2016.

When you get to generating end of December and beginning of January weeks, check to be sure that people on odd- or even-week master schedules are actually scheduled on alternating weeks (not every week).

Keep me posted later in the year on how this works… no hurry.

Thanks,
Allen

<addWeek.php>
<calendar.inc>
<calendar.php>
<viewSchedule.php>

On Oct 15, 2015, at 3:33 PM, gnoonan <notifications@github.com<mailto:notifications@github.com>> wrote:

Thank you Allen! Glad you caught it now. I would ask how, but I’m sure I wouldn’t follow . . .
Hope you’re well!
-Gretchen

**Comment by gnoonan** [comment]
A very creative solution!  Thanks a million Allen.
-Gretchen
