### ISSUE TITLE
Printing Volunteer Applications 

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#8]
We are having trouble printing volunteer applications that are coming in from online. Its almost like we are only getting a screen shot of the application and we miss out on any information that you would need to scroll down to see. Ashley thought larger blocks in a couple areas could be a quick fix, email would be an example. Thanks.

**Comment by megandalster** [comment]
I have fixed this so that an application pops up in a separate browser window.  When you see it there, you can just print it or save it as a PDF, just like any other browser window.  Changes will be sent to Dave Tripp later today for installation on your live Homebase system.

**Comment by gnoonan** [comment]
Great, thanks!

Raymond Ruby
House Manager

Ronald McDonald House Charities of Maine
250 Brackett Street, Portland, ME 04102
Phone 207-780-6282  ext. 316
Fax  207-780-0198
www.rmhcmaine.orghttp://www.rmhcmaine.org/

Don't miss the purses, accessories, gift certificates, and much more  at our 11th Annual Purses with Purpose, etc. luncheonon Thursday, June 2 in Falmouth!http://rmhcmaine.org/10th-annual-purses-with-purpose-etc-funraiser/
