### ISSUE TITLE
Volunteer's profile

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#9]
I've noticed that you can not back space out of a volunteer's profile without it showing an error message. So for example, if I opened up someones profile to look at a piece of information, I cant just go back to the screen before.

**Comment by oradwan** [comment]
Do you have the exact error message / a page I can hit to reproduce it? (I haven't had the full application set up locally for debugging in... 9 years, I think)

**Comment by megandalster** [comment]
With the fix to issue #8, this one is fixed too.  That is, the profile is in a separate page, so if you just close that page the previous page will still be there.
